### ISSUE TITLE
Fix browser export for non-module loader environments

### ISSUE THREAD

**Issue by jamesplease** [jmeas/moment-business#45]
It seems to currently be exporting as `window.none`. Note that this only affects users who _aren't_ using a module bundler like CJS, AMD, or ES2015 modules. If you _are_ using those module bundlers, then you're good to go.

**Comment by leobetosouza** [comment]
So, when this will be in the current version?

**Comment by jamesplease** [comment]
I'm pretty busy, so I won't have time to fix this myself atm. If anyone wanted to look into the build system and open a PR, I'd gladly merge it. Using the latest [generator-babel-boilerplate](https://github.com/babel/generator-babel-boilerplate) gulpfile ([src here](https://github.com/babel/generator-babel-boilerplate/blob/master/app/templates/gulpfile.js)) as a reference would probably fix it.

I strongly recommend that people use module loaders, though.

**Comment by leobetosouza** [comment]
PR done ;)

#47

**Comment by jamesplease** [comment]
Resolved in #47 / #48 

Thank you so much @leobetosouza !

**Comment by neal-eiger** [comment]
Im using systemjs with angular 2 with node_modules am getting this error which seems related to the fix above.  However, Im using version 3.0.1, so seems this is not fixed?

error TS2307: Cannot find module 'moment-business'.

I declared moment-business to be of type any, so i dont think this is a typescript issue, it seems the way its exported isnt working with systemjs.  Ive not had a lot of time to look into it so wanted to check, should this be working currently version 3.0.1 per the merge noted above?
